- earn/README.md
- earn/strategies.json
- earn/strategies.schema.json
Update Earn DateTime Format to ISO 8601
and minor tweaks to the schema
> Update Earn DateTime Format

- cms/earn/README.md
- schemas/strategies.schema.json
Update TVL Endpoint Requirements-allows for USD tvl and max tvl.
Tweak descriptions for a few fields.
Remove Trading Vault as a category.
> Update TVL Endpoint Requirements

- cms/earn/strategies.json
Update Earn Osmosis staking ID from osmosis-staking to osmo-staking
> Update Earn Osmosis staking ID

- cms/earn/README.md
- cms/earn/strategies.json
- schemas/strategies.schema.json
Update Strategies CMS:
stablecoin to stablecoins
move riskReportCardURL to top level (outside the array of strategies)
> Update Strategies CMS: stablecoin to stablecoins

- cms/earn/README.md
Add Link to Earn Strategy Report Card Application
with instructions on how to apply.
> Add Link to Earn Strategy Report Card Application

- cms/earn/README.md
- cms/earn/strategies.json
- schemas/strategies.schema.json
Update EARN CMS property names
-`tags` becomes `categories`
-`category` becomes `type`
-`type` becomes `method`
Updated Defining Schema, Strategies JSON, and README to reflect the changes in terminology.
> Update EARN CMS property names

- schemas/strategies.schema.json
Remove examples for strategies.schema.json
since they were causing test failures
> Remove examples for strategies.schema.json

- cms/earn/README.md
- cms/earn/strategies.json
Update description for Blue Chip category
in the schema, and in the README.
> Update description for Blue Chip category

- cms/earn/README.md
- schemas/strategies.schema.json
Update Earn CMS README,
mostly about the Method description and adding method to the example.
make method a required property in the schema
> Update Earn CMS README, (Method description)

- cms/landing-page/README.md
- cms/landing-page/landing-page.json
- schemas/landing-page.schema.json
- schemas/strategies.schema.json
Add pastAirdrops to Landing Page CMS
Adds to definition schema in /schemas/landing-page.schema.json
Adds to landing-page.json schema with actual data,
Adds to /landing-page/README.md, describing how the array is structured
> Add pastAirdrops to Landing Page CMS

- cms/landing-page/landing-page.json
Add DOKI to Landing Page Airdrops
> Add DOKI to Landing Page Airdrops

- cms/earn/strategies.json
Add OSMO Staking Report Card URL
> Add OSMO Staking Report Card URL

- cms/apps/applications.json
Update Margined App URL (to a prettier domain)
> Update Margined App URL

- cms/top-announcement-banner.json
Update top-announcement-banner.json
Add Top Announcement Banner for Survey 
Waiting for the survey to be 'buttoned up'
> Add Top Announcement Banner for Survey 

- cms/top-announcement-banner.json
Update top-announcement-banner.json endDate
> Update top-announcement-banner End Date to Friday

- cms/swap-rotating-banner.json
Update swap-rotating-banner.json to add Levana
> Add Levana Ad Banner

- cms/swap-rotating-banner.json
Update swap-rotating-banner.json to improve the Levana ad banner copy
> Update Levana AD Banner Copy

- cms/earn/strategies.json
> fix: update denom for USDC

- cms/top-announcement-banner.json
Update Announcement Banner (Feature survey Oct '24)
"en": {
"header": "What features and improvements do you want to see next?",
"link": "Vote now"
},
> Update Announcement Banner (Feature survey Oct '24)

- cms/apps/applications.json
> fix: Update TFM URL for App Store

- cms/earn/strategies.json
Remove Membrane Earn Strategy Geoblock
> Remove Membrane Earn Strategy Geoblock

- cms/top-announcement-banner.json
Re-add Start and End date for the top announcement banner
> Re-add Start and End date for the top announcement banner

- cms/top-announcement-banner.json
Temporarily Show Milkyway banner
should only appear on stage
> Temporarily Show Milkyway banner

- cms/top-announcement-banner.json
Reverts osmosis-labs/fe-content#115
> Revert "Temporarily Show Milkyway banner"

- cms/apps/applications.json
> Remove Quasar from Apps Store
